apiVersion: apps/v1
kind: Deployment
metadata:
  name: insta-clone-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: insta-clone-web
  template:
    metadata:
      labels:
        app: insta-clone-web
    spec:
      containers:
        - name: instaclonewebd
          image: docker.io/haungi/insta-clone-web:1.0.0 # {"$imagepolicy": "flux-system:insta-clone-web"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
