apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: insta-clone-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: insta-clone-web
  policy:
    semver:
      range: 1.0.x

